caila:
  accessToken: <PASTE YOUR JAICP API TOKEN>

connection:
  mode: polling
  accessToken: <PASTE YOUR JAICP API TOKEN>

bot:
  onErrorReply: "Sorry, something's happened, I'll have to call you back later!"
  operatorNumber: <SET YOUR OPERATOR NUMBER TO TRANSFER CALLS TO>